name: Deploy to Server on Develop Branch Merge

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t custom-label-studio:latest .

      - name: Tag Docker image
        run: |
          docker tag custom-label-studio:latest darrenkdl/custom-label-studio:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push darrenkdl/custom-label-studio:latest

#      - name: Deploy to server
#        env:
#          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
#          SERVER_USER: ${{ secrets.SERVER_USER }}
#          SERVER_HOST: ${{ secrets.SERVER_HOST }}
#        run: |
#          # Save the private key to a file
#          echo "$SSH_KEY" > ~/.ssh/id_rsa
#          chmod 600 ~/.ssh/id_rsa
#
#          # Pull the latest Docker image on the server and restart the container
#          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "
#            docker pull darrenkdl/custom-label-studio:latest &&
#            docker stop label-studio-connect-postgre || true &&
#            docker rm label-studio-connect-postgre || true &&
#            docker run -d --name label-studio-connect-postgre -p 8080:8080 darrenkdl/custom-label-studio:latest
#          "
